using B2BCommerceDemo.Core.DTOs.Import;
using CsvHelper.Configuration;
using System.Globalization;

namespace B2BCommerceDemo.Infrastructure.Imports
{
    public class ProductImportMap : ClassMap<ProductImportDto>
    {
        public ProductImportMap()
        {
            Map(m => m.Sku).Name("SKU", "Sku", "sku", "SKUNumber", "SKU Number", "SKU_Number", "SkuNumber", "Sku Number", "Sku_Number", "skunumber", "sku number", "sku_number", "ProductNumber", "Product Number", "Product_Number", "productnumber", "product number", "product_number", "ProductNo.", "Product No.", "Product_No.", "Productno.", "Product no.", "Product_no.", "productno.", "product no.", "product_no.");
            Map(m => m.Name).Name("Name", "name", "ProductName", "Product Name", "Product_Name", "productname", "product name", "product_name", "ProductItem", "Product Item", "Product_Item", "productitem", "product item", "product_item");
            Map(m => m.AvailableStock).Name("Available", "available", "AvailableQuantity", "Available Quantity", "Available_Quantity", "availablequantity", "available quantity", "available_quantity", "Stock", "stock", "Quantity", "quantity", "StockQuantity", "Stock Quantity", "Stock_Quantity", "stockquantity", "stock quantity", "stock_quantity", "AvailableStock", "Available Stock", "Available_Stock", "availablestock", "available stock", "available_stock");
            Map(m => m.PurchasedQuantity).Name("Purchased", "purchased", "PurchasedQuantity", "Purchased Quantity", "Purchased_Quantity", "purchasedquantity", "purchased quantity", "purchased_quantity");
            Map(m => m.Ean).Name("EAN", "Ean", "ean", "EANCode", "EAN Code", "EAN_Code", "EanCode", "Ean Code", "Ean_Code", "eancode", "ean code", "ean_code", "EANNumber", "EAN Number", "EAN_Number", "EanNumber", "Ean Number", "Ean_Number", "eanumber", "ean number", "ean_number", "Barcode", "barcode", "BarCode");
            Map(m => m.BasePrice).Name("Price (EUR)", "Price_(EUR)", "price (EUR)", "price_(EUR)", "BasePrice (EUR)", "BasePrice_(EUR)", "Base Price (EUR)", "Base_Price_(EUR)", "Baseprice (EUR)", "Baseprice_(EUR)", "Base price (EUR)", "Base_price_(EUR)", "baseprice (EUR)", "baseprice_(EUR)", "base price (EUR)", "base_price_(EUR)", "SalesPrice (EUR)", "SalesPrice_(EUR)", "Sales Price (EUR)", "Sales_Price_(EUR)", "Sales price (EUR)", "Sales_price_(EUR)", "salesprice (EUR)", "salesprice_(EUR)", "sales price (EUR)", "sales_price_(EUR)", "ProductPrice (EUR)", "ProductPrice_(EUR)", "Product Price (EUR)", "Product_Price_(EUR)", "productprice (EUR)", "productprice_(EUR)", "product price (EUR)", "product_price_(EUR)").TypeConverterOption.CultureInfo(new CultureInfo("da-DK"));
            Map(m => m.Brand).Name("Brand", "brand", "BrandName", "Brand Name", "Brand_Name", "Brandname", "Brand name", "Brand_name", "brandname", "brand name", "brand_name", "Producer", "producer", "ProducerName", "Producer Name", "Producer_Name", "Producername", "Producer name", "Producer_name", "producername", "producer name", "producer_name", "Manufacturer", "manufacturer", "ManufacturerName", "Manufacturer Name", "Manufacturer_Name", "Manufacturername", "Manufacturer name", "Manufacturer_name", "manufacturername", "manufacturer name", "manufacturer_name");
            Map(m => m.Category).Name("Category", "category", "CategoryName", "Category Name", "Category_Name", "Categoryname", "Category name", "Category_name", "categoryname", "category name", "category_name", "ProductCategory", "Product Category", "Product_Category", "Productcategory", "Product category", "Product_category", "productcategory", "product category", "product_category", "ItemCategory", "ItemCategory", "Item Category", "Item_Category", "Itemcategory", "Item category", "Item_category", "itemcategory", "item category", "item_category");
            Map(m => m.ImageUrl).Name("Image", "image", "URL", "Url", "url", "ImageURL", "Image URL", "Image_URL", "ImageUrl", "Image Url", "Image_Url", "Imageurl", "Image url", "Image_url", "imageURL", "image URL", "image_URL", "imageUrl", "image Url", "image_Url", "imageurl", "image url", "image_url", "Picture", "picture", "ProductURL", "Product URL", "Product_URL", "ProductUrl", "Product Url", "Product_Url", "Producturl", "Product url", "Product_url", "productURL", "product URL", "product_URL", "productUrl", "product Url", "product_Url", "producturl", "product url", "product_url");
            Map(m => m.ExpectedDeliveryDate).Name("ExpectedDeliveryDate", "Expected Delivery Date", "Expected_Delivery_Date", "Expecteddeliverydate", "Expected delivery date", "Expected_delivery_date", "expecteddeliverydate", "expected delivery date", "expected_delivery_date", "PreferredDeliveryDate", "Preferred Delivery Date", "Preferred_Delivery_Date", "Preferreddeliverydate", "Preferred delivery date", "Preferred_delivery_date", "preferreddeliverydate", "preferred delivery date", "preferred_delivery_date").TypeConverterOption.Format("dd/MM/yyyy", "dd-MM-yyyy", "MM/dd/yyyy", "MM-dd-yyyy", "yyyy/MM/dd", "yyyy-MM-dd");
        }
    }
}

